### ISSUE TITLE
`getTemplate` broken when parsing multiple templates

### ISSUE THREAD

**Issue by timkelty** [umakantp/jsmart#12] opened 2015-04-07 17:59 UTC
In a situation where you're parsing multiple files through jSmart, I've found that in the event that your template has an `extends` tag, only the first one get parsed correctly.

This occurs when using in a build process like:
https://github.com/timkelty/gulp-jsmart
https://github.com/hereandnow/grunt-jsmart

I've found that if I add `nocache = true;` to the top of the `getTemplate` function, things seem to work fine.

Any idea?

Possibly related to: https://github.com/umakantp/jsmart/issues/11

**Comment by umakantp** [comment] 2015-08-10 12:23
Duplicate of https://github.com/umakantp/jsmart/issues/11

**Comment by AustP** [comment] 2016-01-20 20:28
Having this issue as well. This bug makes jSmart unusable for me.

**Comment by Avcajaraville** [comment] 2016-04-07 15:46
Yeah, the same for me. Any update here ? Does anybody knows how to fix this issue ?

**Comment by umakantp** [comment] 2017-08-11 09:23
Parent issue has been fixed and close:-

This has been fixed in  the release v2.15.1

**Closed by umakantp** 2017-08-11 09:23 UTC
Labels: duplicate
